switch back to bash

diff --git a/.config/sh/shrc b/.config/sh/shrc
--- a/.config/sh/shrc
+++ b/.config/sh/shrc
@@ -10,44 +10,15 @@ alias poweroff="sudo /sbin/poweroff"
 # make startx use $XDG_CONFIG_HOME/x11/xsession
 alias startx="xinit $XDG_CONFIG_HOME/x11/xsession -- vt$(tty | tail -c2)"
 
-# FIXME: needs more testing!!
-# setup a PS1 that *should* work in any POSIX compliant shell
 __git_prompt() {
     BRANCH="$(git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ [\1]/')"
-    [ "$(git ls-files 2>/dev/null | wc -l)" -lt 1000 ] && STATUS="$(git status --short 2>/dev/null | sed 's/^ //g' | cut -d' ' -f1 | sort -u | tr -d '\n' | sed 's/\(.*\)/[\1]/')" || STATUS="[NOSTAT]"
+    [ "$(git ls-files 2>/dev/null | wc -l)" -lt 1000 ] && \
+        STATUS="$(git status --short 2>/dev/null | sed 's/^ //g' | cut -d' ' -f1 | sort -u | tr -d '\n' | sed 's/\(.*\)/[\1]/')" || STATUS="[NOSTAT]"
     printf "%s%s" "$BRANCH" "$STATUS"
 }
 
-# FreeBSD's ash can't eval in the prompt
-if [ "$(uname)" != "FreeBSD" ] || [ -n "$KSH_VERSION" ]; then
-    PS1="$USER@${HOSTNAME:=$(hostname)}:\$(pwd | sed -e 's/\/usr\/home\/'$USER'/~/' -e 's/\/home\/'$USER'/~/')\$(__git_prompt)> "
-else
-    PS1="$USER@${HOSTNAME:=$(hostname)}> "
-fi
+PS1="$USER@${HOSTNAME:=$(hostname)}:\$(pwd | sed -e 's/\/usr\/home\/'$USER'/~/' -e 's/\/home\/'$USER'/~/')\$(__git_prompt)> "
 
-# common history file
-HISTFILE="$XDG_DATA_HOME/history"
-
-# ksh wants to delete history by default, rein it in
-[ -n "$KSH_VERSION" ] && HISTSIZE=100000
-
-# cleanup on exit
-__cleanup() {
-    rmdir ~/*
-    rm ~/.*hist*
-    rm ~/.lesshst
-    rm ~/.viminfo
-    rm -rf ~/.cache
-    rm -rf ~/.w3m
-    # delete duplicate lines & lines starting with space
-    awk '!/^ /&&!x[$0]++' "$XDG_DATA_HOME/history" "$XDG_DATA_HOME/bash-history" > "$XDG_CACHE_HOME/cleaned_history" \
-        && mv "$XDG_CACHE_HOME/cleaned_history" "$XDG_DATA_HOME/history"
-    clear
-}
-
-trap __cleanup EXIT
-
-# nice features in bash
 if [ -n "$BASH_VERSION" ]; then
     # source bash-completion
     if [ -f /usr/share/bash-completion/bash_completion ]; then
@@ -66,29 +37,24 @@ if [ -n "$BASH_VERSION" ]; then
     # check the window size after each command and, if necessary, update
     # the values of LINES and COLUMNS.
     shopt -s checkwinsize
+
+    # better completion (imo)
+    bind "set menu-complete-display-prefix on"
+    bind "set show-all-if-ambiguous on"
+    bind "set completion-query-items 0"
+    bind "TAB:menu-complete"
+    bind "\"\e[Z\": menu-complete-backward"
 fi
 
-# and nice features in zsh
-if [ -n "$ZSH_VERSION" ]; then
-    bindkey -e
-    bindkey '^[[Z' reverse-menu-complete
-    set -o no_hup
-    set -o inc_append_history
-    set -o hist_ignore_all_dups
-    set -o hist_ignore_space
-    SAVEHIST=100000
-    HISTSIZE=100000
-    HISTFILE="$XDG_DATA_HOME/zsh-history"
-    zle_highlight+=(paste:none)
+# cleanup on exit
+__cleanup() {
+    rm -rf ~/.cache 2>/dev/null
+    rm ~/.*hist* 2>/dev/null
+    rm ~/.*wget* 2>/dev/null
+    rm ~/.lesshst 2>/dev/null
+    rm ~/.viminfo 2>/dev/null
+    rmdir ~/* 2>/dev/null
+    clear
+}
 
-    # by default you can't open URLs with '?' in them...
-    set -o no_nomatch
-
-    # enable better compeletion
-    autoload -Uz compinit && compinit -d "$XDG_DATA_HOME/zcompdump"
-    zstyle ':completion:*' rehash true
-
-    # no idea how zsh's PROMPT works, so use PS1
-    set -o prompt_subst
-    PS1='%n@%m:%~%f$(__git_prompt)> '
-fi
+trap __cleanup EXIT
